### ISSUE TITLE
Add ability to specify version of npm that should be used

### ISSUE THREAD

**Issue by vladikoff** [pdehaan/npmshrink#2]
Can we add a thing that only runs shrinkwrap if the user is using the correct version of npm.

Example: `npm --version` -> `2`

`npmshrink --npm-version=3`

```
Error: You must use npm 3 to run this script
```

Thoughts?

**Comment by pdehaan** [comment]
@vladikoff PRs welcome!

**Comment by vladikoff** [comment]
Something like this, where the npm engine is set https://github.com/mozilla/fxa-oauth-server/pull/531 and then if you try to wrap with an unmatched version it should fail.
